### ISSUE TITLE
[security] Insecure random function used

### ISSUE THREAD

**Issue by Rotzbua** [scoutnet/plugins.sn_webservice#6]
`rand` is not a crypto safe function. Do not use it with cryptographic stuff.

```php
        // Generate random first block, which is deleted on the reciever side.
        // This is done since we use the same iv all the time.
        $first_block = '';
        for ($i = 0; $i < 16; $i++) {
            $first_block .= chr(rand(0, 255));
        }
```
Found at https://github.com/scoutnet/plugins.sn_webservice/blob/master/Classes/ScoutnetApi.php#L439

**Comment by sHorst** [comment]
this is for an iv only, which is semi public. so we can use rand here. i grant you that we disclose some pseudo random state with 16 consecutive bytes. but since this is encryped anyway we can ignore this ..
